# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.14

# Fabric API
fabric_version=0.123.2+1.21.5

# Mod Properties
mod_version = 1.9.0
maven_group = cn.disy920
archives_base_name = fabricproxy
